version: "3.9"

services:
  jenkins:
    image: jenkins/jenkins:lts
    # Run as root so we can apt‑get Node later
    user: root
    container_name: jenkins-Task-8.1
    ports:
      - "8080:8080"          # Web UI
      - "50000:50000"        # JNLP agents (future‑proof)
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   # allow Docker‑in‑Docker builds
    restart: unless-stopped
    # Optional proxy / DNS fix if your campus network is strict:
    # environment:
    #   - JAVA_OPTS=-Duser.timezone=Australia/Melbourne

volumes:
  jenkins_home:
